FROM apache/airflow:2.9.1-python3.10

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev default-jre-headless && rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements-pipeline.txt /tmp/requirements-pipeline.txt
RUN pip install --no-cache-dir -r /tmp/requirements-pipeline.txt

WORKDIR /opt/airflow/app
COPY . .
